name: Deploy to DreamHost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Deploy via SFTP
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          DEPLOY_PATH: subdomain.domain.tld/ # Change this to your project path
        run: |
          lftp -u $USERNAME,$PASSWORD sftp://$HOST -e "
          set sftp:auto-confirm yes;
          mirror --reverse --delete --verbose --exclude .git/ ./ $DEPLOY_PATH; quit"
